apiVersion: v1
kind: Service
metadata:
  name: finflow-tradereco-service
  labels:
    app: finflow-tradereco
spec:
  type: NodePort
  selector:
    app: finflow-tradereco
  ports:
    - nodePort: 30009
      port: 8112
      targetPort: 8112